/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/_client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientTabsRouteImport } from './routes/_authenticated/_client/_tabs'
import { Route as AuthenticatedClientBookRouteImport } from './routes/_authenticated/_client/book'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedClientTabsProfileRouteImport } from './routes/_authenticated/_client/_tabs/profile'
import { Route as AuthenticatedAdminProfessionalsIndexRouteImport } from './routes/_authenticated/admin/professionals/index'
import { Route as AuthenticatedAdminProfessionalsIdRouteImport } from './routes/_authenticated/admin/professionals/$id'
import { Route as AuthenticatedAdminQueueIndexRouteImport } from './routes/_authenticated/admin/queue/index'
import { Route as AuthenticatedAdminQueueIdRouteImport } from './routes/_authenticated/admin/queue/$id'
import { Route as AuthenticatedClientTabsAppointmentsIndexRouteImport } from './routes/_authenticated/_client/_tabs/appointments/index'
import { Route as AuthenticatedClientTabsAppointmentsIdRouteImport } from './routes/_authenticated/_client/_tabs/appointments/$id'
import { Route as AuthenticatedClientAppointmentsIdAddItemRouteImport } from './routes/_authenticated/_client/appointments/$id/add-item'
import { Route as AuthenticatedClientAppointmentsIdItemsItemIdRepositionRouteImport } from './routes/_authenticated/_client/appointments/$id/items/$itemId/reposition'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientTabsRoute = AuthenticatedClientTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AuthenticatedClientRoute,
} as any)
const AuthenticatedClientBookRoute = AuthenticatedClientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedClientRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientTabsProfileRoute =
  AuthenticatedClientTabsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedClientTabsRoute,
  } as any)
const AuthenticatedAdminProfessionalsIndexRoute =
  AuthenticatedAdminProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfessionalsIdRoute =
  AuthenticatedAdminProfessionalsIdRouteImport.update({
    id: '/professionals/$id',
    path: '/professionals/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQueueIndexRoute =
  AuthenticatedAdminQueueIndexRouteImport.update({
    id: '/queue/',
    path: '/queue/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQueueIdRoute =
  AuthenticatedAdminQueueIdRouteImport.update({
    id: '/queue/$id',
    path: '/queue/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientTabsAppointmentsIndexRoute =
  AuthenticatedClientTabsAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedClientTabsRoute,
  } as any)
const AuthenticatedClientTabsAppointmentsIdRoute =
  AuthenticatedClientTabsAppointmentsIdRouteImport.update({
    id: '/appointments/$id',
    path: '/appointments/$id',
    getParentRoute: () => AuthenticatedClientTabsRoute,
  } as any)
const AuthenticatedClientAppointmentsIdAddItemRoute =
  AuthenticatedClientAppointmentsIdAddItemRouteImport.update({
    id: '/appointments/$id/add-item',
    path: '/appointments/$id/add-item',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute =
  AuthenticatedClientAppointmentsIdItemsItemIdRepositionRouteImport.update({
    id: '/appointments/$id/items/$itemId/reposition',
    path: '/appointments/$id/items/$itemId/reposition',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/book': typeof AuthenticatedClientBookRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedClientTabsProfileRoute
  '/admin/professionals/$id': typeof AuthenticatedAdminProfessionalsIdRoute
  '/admin/queue/$id': typeof AuthenticatedAdminQueueIdRoute
  '/admin/professionals/': typeof AuthenticatedAdminProfessionalsIndexRoute
  '/admin/queue/': typeof AuthenticatedAdminQueueIndexRoute
  '/appointments/$id': typeof AuthenticatedClientTabsAppointmentsIdRoute
  '/appointments/$id/add-item': typeof AuthenticatedClientAppointmentsIdAddItemRoute
  '/appointments/': typeof AuthenticatedClientTabsAppointmentsIndexRoute
  '/appointments/$id/items/$itemId/reposition': typeof AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/book': typeof AuthenticatedClientBookRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedClientTabsProfileRoute
  '/admin/professionals/$id': typeof AuthenticatedAdminProfessionalsIdRoute
  '/admin/queue/$id': typeof AuthenticatedAdminQueueIdRoute
  '/admin/professionals': typeof AuthenticatedAdminProfessionalsIndexRoute
  '/admin/queue': typeof AuthenticatedAdminQueueIndexRoute
  '/appointments/$id': typeof AuthenticatedClientTabsAppointmentsIdRoute
  '/appointments/$id/add-item': typeof AuthenticatedClientAppointmentsIdAddItemRoute
  '/appointments': typeof AuthenticatedClientTabsAppointmentsIndexRoute
  '/appointments/$id/items/$itemId/reposition': typeof AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_client/_tabs': typeof AuthenticatedClientTabsRouteWithChildren
  '/_authenticated/_client/book': typeof AuthenticatedClientBookRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/_client/_tabs/profile': typeof AuthenticatedClientTabsProfileRoute
  '/_authenticated/admin/professionals/$id': typeof AuthenticatedAdminProfessionalsIdRoute
  '/_authenticated/admin/queue/$id': typeof AuthenticatedAdminQueueIdRoute
  '/_authenticated/admin/professionals/': typeof AuthenticatedAdminProfessionalsIndexRoute
  '/_authenticated/admin/queue/': typeof AuthenticatedAdminQueueIndexRoute
  '/_authenticated/_client/_tabs/appointments/$id': typeof AuthenticatedClientTabsAppointmentsIdRoute
  '/_authenticated/_client/appointments/$id/add-item': typeof AuthenticatedClientAppointmentsIdAddItemRoute
  '/_authenticated/_client/_tabs/appointments/': typeof AuthenticatedClientTabsAppointmentsIndexRoute
  '/_authenticated/_client/appointments/$id/items/$itemId/reposition': typeof AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/book'
    | '/admin/services'
    | '/admin/'
    | '/profile'
    | '/admin/professionals/$id'
    | '/admin/queue/$id'
    | '/admin/professionals/'
    | '/admin/queue/'
    | '/appointments/$id'
    | '/appointments/$id/add-item'
    | '/appointments/'
    | '/appointments/$id/items/$itemId/reposition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/book'
    | '/admin/services'
    | '/admin'
    | '/profile'
    | '/admin/professionals/$id'
    | '/admin/queue/$id'
    | '/admin/professionals'
    | '/admin/queue'
    | '/appointments/$id'
    | '/appointments/$id/add-item'
    | '/appointments'
    | '/appointments/$id/items/$itemId/reposition'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_client'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/_client/_tabs'
    | '/_authenticated/_client/book'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/'
    | '/_authenticated/_client/_tabs/profile'
    | '/_authenticated/admin/professionals/$id'
    | '/_authenticated/admin/queue/$id'
    | '/_authenticated/admin/professionals/'
    | '/_authenticated/admin/queue/'
    | '/_authenticated/_client/_tabs/appointments/$id'
    | '/_authenticated/_client/appointments/$id/add-item'
    | '/_authenticated/_client/_tabs/appointments/'
    | '/_authenticated/_client/appointments/$id/items/$itemId/reposition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_client/_tabs': {
      id: '/_authenticated/_client/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientTabsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/book': {
      id: '/_authenticated/_client/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedClientBookRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_client/_tabs/profile': {
      id: '/_authenticated/_client/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedClientTabsProfileRouteImport
      parentRoute: typeof AuthenticatedClientTabsRoute
    }
    '/_authenticated/admin/professionals/': {
      id: '/_authenticated/admin/professionals/'
      path: '/professionals'
      fullPath: '/admin/professionals/'
      preLoaderRoute: typeof AuthenticatedAdminProfessionalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/professionals/$id': {
      id: '/_authenticated/admin/professionals/$id'
      path: '/professionals/$id'
      fullPath: '/admin/professionals/$id'
      preLoaderRoute: typeof AuthenticatedAdminProfessionalsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/queue/': {
      id: '/_authenticated/admin/queue/'
      path: '/queue'
      fullPath: '/admin/queue/'
      preLoaderRoute: typeof AuthenticatedAdminQueueIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/queue/$id': {
      id: '/_authenticated/admin/queue/$id'
      path: '/queue/$id'
      fullPath: '/admin/queue/$id'
      preLoaderRoute: typeof AuthenticatedAdminQueueIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_client/_tabs/appointments/': {
      id: '/_authenticated/_client/_tabs/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedClientTabsAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedClientTabsRoute
    }
    '/_authenticated/_client/_tabs/appointments/$id': {
      id: '/_authenticated/_client/_tabs/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AuthenticatedClientTabsAppointmentsIdRouteImport
      parentRoute: typeof AuthenticatedClientTabsRoute
    }
    '/_authenticated/_client/appointments/$id/add-item': {
      id: '/_authenticated/_client/appointments/$id/add-item'
      path: '/appointments/$id/add-item'
      fullPath: '/appointments/$id/add-item'
      preLoaderRoute: typeof AuthenticatedClientAppointmentsIdAddItemRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/appointments/$id/items/$itemId/reposition': {
      id: '/_authenticated/_client/appointments/$id/items/$itemId/reposition'
      path: '/appointments/$id/items/$itemId/reposition'
      fullPath: '/appointments/$id/items/$itemId/reposition'
      preLoaderRoute: typeof AuthenticatedClientAppointmentsIdItemsItemIdRepositionRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
  }
}

interface AuthenticatedClientTabsRouteChildren {
  AuthenticatedClientTabsProfileRoute: typeof AuthenticatedClientTabsProfileRoute
  AuthenticatedClientTabsAppointmentsIdRoute: typeof AuthenticatedClientTabsAppointmentsIdRoute
  AuthenticatedClientTabsAppointmentsIndexRoute: typeof AuthenticatedClientTabsAppointmentsIndexRoute
}

const AuthenticatedClientTabsRouteChildren: AuthenticatedClientTabsRouteChildren =
  {
    AuthenticatedClientTabsProfileRoute: AuthenticatedClientTabsProfileRoute,
    AuthenticatedClientTabsAppointmentsIdRoute:
      AuthenticatedClientTabsAppointmentsIdRoute,
    AuthenticatedClientTabsAppointmentsIndexRoute:
      AuthenticatedClientTabsAppointmentsIndexRoute,
  }

const AuthenticatedClientTabsRouteWithChildren =
  AuthenticatedClientTabsRoute._addFileChildren(
    AuthenticatedClientTabsRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientTabsRoute: typeof AuthenticatedClientTabsRouteWithChildren
  AuthenticatedClientBookRoute: typeof AuthenticatedClientBookRoute
  AuthenticatedClientAppointmentsIdAddItemRoute: typeof AuthenticatedClientAppointmentsIdAddItemRoute
  AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute: typeof AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientTabsRoute: AuthenticatedClientTabsRouteWithChildren,
  AuthenticatedClientBookRoute: AuthenticatedClientBookRoute,
  AuthenticatedClientAppointmentsIdAddItemRoute:
    AuthenticatedClientAppointmentsIdAddItemRoute,
  AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute:
    AuthenticatedClientAppointmentsIdItemsItemIdRepositionRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProfessionalsIdRoute: typeof AuthenticatedAdminProfessionalsIdRoute
  AuthenticatedAdminQueueIdRoute: typeof AuthenticatedAdminQueueIdRoute
  AuthenticatedAdminProfessionalsIndexRoute: typeof AuthenticatedAdminProfessionalsIndexRoute
  AuthenticatedAdminQueueIndexRoute: typeof AuthenticatedAdminQueueIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProfessionalsIdRoute:
    AuthenticatedAdminProfessionalsIdRoute,
  AuthenticatedAdminQueueIdRoute: AuthenticatedAdminQueueIdRoute,
  AuthenticatedAdminProfessionalsIndexRoute:
    AuthenticatedAdminProfessionalsIndexRoute,
  AuthenticatedAdminQueueIndexRoute: AuthenticatedAdminQueueIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
