/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gera o token CSRF (e o cookie que o acompanha) */
        get: operations["AuthController_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastra um cliente e já abre a sessão */
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre a sessão (cookies HttpOnly) */
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca o refresh token por um par novo (rotação) */
        post: operations["AuthController_renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão e revoga o refresh token */
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário da sessão atual */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os serviços, paginada (inativos só para administradores) */
        get: operations["ServicesController_list"];
        put?: never;
        /** Cadastra um serviço (administrador) */
        post: operations["ServicesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera ou ativa/desativa um serviço (administrador) */
        patch: operations["ServicesController_update"];
        trace?: never;
    };
    "/api/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os profissionais, paginada (opcionalmente os que fazem um serviço) */
        get: operations["ProfessionalsController_list"];
        put?: never;
        /** Cadastra um profissional (administrador) */
        post: operations["ProfessionalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe: serviços que executa e expediente semanal */
        get: operations["ProfessionalsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera ou ativa/desativa um profissional (administrador) */
        patch: operations["ProfessionalsController_update"];
        trace?: never;
    };
    "/api/professionals/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Define os serviços que o profissional executa (administrador) */
        put: operations["ProfessionalsController_replaceServices"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professionals/{id}/working-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Define o expediente semanal do profissional (administrador) */
        put: operations["ProfessionalsController_replaceWorkingHours"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista agendamentos (cliente: os seus; administrador: todos) */
        get: operations["AppointmentsController_list"];
        put?: never;
        /** Cria um agendamento (cliente) */
        post: operations["AppointmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do agendamento */
        get: operations["AppointmentsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linha do tempo do agendamento (administrador) */
        get: operations["AppointmentsController_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adiciona um item ao agendamento (dono na janela / administrador) */
        post: operations["AppointmentsController_addAppointmentItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reposiciona um item do agendamento (dono na janela / administrador) */
        patch: operations["AppointmentsController_repositionAppointmentItem"];
        trace?: never;
    };
    "/api/appointments/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma todos os itens aguardando confirmação (administrador) */
        post: operations["AppointmentsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela o agendamento (dono na janela / administrador) */
        post: operations["AppointmentsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/items/{itemId}/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Muda o status operacional de um item (administrador) */
        post: operations["AppointmentsController_changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}/items/{itemId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela um item (dono na janela / administrador) */
        post: operations["AppointmentsController_cancelAppointmentItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Horários de início disponíveis para uma cadeia de itens em uma data */
        get: operations["AvailabilityController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parâmetros de negócio do agendamento */
        get: operations["ConfigController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Painel gerencial semanal, com comparação com a semana anterior */
        get: operations["ReportsController_weekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateProfileDto: {
            /**
             * @description Guardado no formato internacional (+5511912345678). Envie null para remover
             * @example (11) 91234-5678
             */
            phone?: string | null;
            name?: string;
        };
        UserResponse: {
            /** @example +5511912345678 */
            phone: string | null;
            id: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "CLIENT" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
        };
        CsrfResponse: {
            csrfToken: string;
        };
        RegisterDto: {
            /**
             * @description Guardado no formato internacional (+5511912345678)
             * @example (11) 91234-5678
             */
            phone?: string;
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        ServiceResponse: {
            /**
             * @description Minutos
             * @example 60
             */
            durationMinutes: number;
            /**
             * @description Centavos
             * @example 8000
             */
            priceCents: number;
            id: string;
            name: string;
            active: boolean;
        };
        ServicePageResponse: {
            items: components["schemas"]["ServiceResponse"][];
            /**
             * @description Total de itens em todas as páginas
             * @example 42
             */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 3 */
            totalPages: number;
        };
        CreateServiceDto: {
            /** @example Corte feminino */
            name: string;
            /**
             * @description Duração em minutos (múltiplo de 15, de 15 a 480)
             * @example 60
             */
            durationMinutes: number;
            /**
             * @description Preço em centavos (8000 = R$ 80,00)
             * @example 8000
             */
            priceCents: number;
        };
        UpdateServiceDto: {
            /** @example Corte feminino */
            name?: string;
            /**
             * @description Duração em minutos (múltiplo de 15, de 15 a 480)
             * @example 60
             */
            durationMinutes?: number;
            /**
             * @description Preço em centavos (8000 = R$ 80,00)
             * @example 8000
             */
            priceCents?: number;
            /** @example true */
            active?: boolean;
        };
        ProfessionalResponse: {
            id: string;
            name: string;
            active: boolean;
        };
        ProfessionalPageResponse: {
            items: components["schemas"]["ProfessionalResponse"][];
            /**
             * @description Total de itens em todas as páginas
             * @example 42
             */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 3 */
            totalPages: number;
        };
        WorkingWindowResponse: {
            /**
             * @description 1 = segunda ... 7 = domingo
             * @example 1
             */
            weekday: number;
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
        };
        ProfessionalDetailResponse: {
            serviceIds: string[];
            workingHours: components["schemas"]["WorkingWindowResponse"][];
            id: string;
            name: string;
            active: boolean;
        };
        CreateProfessionalDto: {
            /** @example Ana Souza */
            name: string;
        };
        UpdateProfessionalDto: {
            /** @example Ana Souza */
            name?: string;
            /** @example true */
            active?: boolean;
        };
        SetServicesDto: {
            /**
             * @description Substitui os serviços do profissional. Lista vazia remove todos
             * @example [
             *       "01M30K8EVJW30BGBPJX78A3GHM"
             *     ]
             */
            serviceIds: string[];
        };
        WorkingWindowDto: {
            /**
             * @description 1 = segunda ... 7 = domingo
             * @example 1
             */
            weekday: number;
            /** @example 09:00 */
            startTime: string;
            /** @example 18:00 */
            endTime: string;
        };
        SetWorkingHoursDto: {
            /** @description Substitui o expediente semanal. Várias faixas no mesmo dia permitem pausa (ex.: almoço). Lista vazia remove tudo */
            windows: components["schemas"]["WorkingWindowDto"][];
        };
        AppointmentItemInputDto: {
            /** @example 01M30K8EVJW30BGBPJX78A3GHM */
            serviceId: string;
            /** @example 01M30K8EVJW30BGBPJX78A3GHM */
            professionalId: string;
        };
        CreateAppointmentDto: {
            /**
             * Format: date-time
             * @description Início do primeiro item, na grade de 30 min
             * @example 2026-10-01T15:00:00Z
             */
            startsAt: string;
            /** @example Alergia a produtos com amônia */
            notes?: string;
            items: components["schemas"]["AppointmentItemInputDto"][];
        };
        ServiceRefResponse: {
            id: string;
            name: string;
        };
        ProfessionalRefResponse: {
            id: string;
            name: string;
        };
        AppointmentItemResponse: {
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "NO_SHOW";
            id: string;
            service: components["schemas"]["ServiceRefResponse"];
            professional: components["schemas"]["ProfessionalRefResponse"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            priceCents: number;
        };
        ClientResponse: {
            id: string;
            name: string;
            phone: string | null;
        };
        AppointmentResponse: {
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "IN_PROGRESS" | "FINISHED" | "CANCELLED";
            items: components["schemas"]["AppointmentItemResponse"][];
            id: string;
            client: components["schemas"]["ClientResponse"];
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            totalCents: number;
            /** Format: date-time */
            changeDeadline: string | null;
            canClientChange: boolean;
        };
        AppointmentPageResponse: {
            items: components["schemas"]["AppointmentResponse"][];
            /**
             * @description Total de itens em todas as páginas
             * @example 42
             */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 3 */
            totalPages: number;
        };
        HistoryActorResponse: {
            id: string;
            name: string;
        };
        AppointmentHistoryEntryResponse: {
            /** @enum {string} */
            action: "ITEM_ADDED" | "ITEM_REPOSITIONED" | "ITEM_STATUS_CHANGED";
            id: string;
            itemId: string;
            actor: components["schemas"]["HistoryActorResponse"];
            changes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurredAt: string;
        };
        AddItemDto: {
            /** @example 01M30K8EVJW30BGBPJX78A3GHM */
            serviceId: string;
            /** @example 01M30K8EVJW30BGBPJX78A3GHM */
            professionalId: string;
            /**
             * Format: date-time
             * @description Início do item, na grade de 30 min
             * @example 2026-10-01T16:00:00Z
             */
            startsAt: string;
        };
        RepositionItemDto: {
            /**
             * Format: date-time
             * @description Novo início do item, na grade de 30 min
             * @example 2026-10-01T16:00:00Z
             */
            startsAt: string;
            /** @example 01M30K8EVJW30BGBPJX78A3GHM */
            professionalId?: string;
        };
        CancelDto: {
            /** @example Imprevisto de última hora */
            reason?: string;
        };
        SameWeekSuggestionResponse: {
            starts: string[];
            date: string;
        };
        AvailabilityResponse: {
            starts: string[];
            sameWeekSuggestion?: components["schemas"]["SameWeekSuggestionResponse"] | null;
            date: string;
        };
        ConfigResponse: {
            utcOffsetMinutes: number;
            slotMinutes: number;
            minLeadHours: number;
            maxDaysAhead: number;
            changeWindowHours: number;
        };
        WeeklyReportPeriodResponse: {
            revenueCents: number;
            completedCount: number;
            createdCount: number;
            cancellationRate: number;
            noShowRate: number;
        };
        ServiceRankingResponse: {
            serviceId: string;
            name: string;
            completedCount: number;
        };
        ProfessionalOccupancyResponse: {
            professionalId: string;
            name: string;
            scheduledMinutes: number;
            workingMinutes: number;
            occupancyRate: number | null;
        };
        RevenueByWeekdayResponse: {
            weekday: number;
            revenueCents: number;
        };
        WeeklyReportResponse: {
            weekStart: string;
            weekEnd: string;
            current: components["schemas"]["WeeklyReportPeriodResponse"];
            previous: components["schemas"]["WeeklyReportPeriodResponse"];
            serviceRanking: components["schemas"]["ServiceRankingResponse"][];
            professionalOccupancy: components["schemas"]["ProfessionalOccupancyResponse"][];
            revenueByWeekday: components["schemas"]["RevenueByWeekdayResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    AuthController_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    AuthController_renew: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    ServicesController_list: {
        parameters: {
            query?: {
                /** @description Página, começando em 1 */
                page?: number;
                /** @description Itens por página (máximo 100) */
                limit?: number;
                /** @description Só tem efeito para administradores */
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicePageResponse"];
                };
            };
        };
    };
    ServicesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
        };
    };
    ServicesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
        };
    };
    ProfessionalsController_list: {
        parameters: {
            query?: {
                /** @description Página, começando em 1 */
                page?: number;
                /** @description Itens por página (máximo 100) */
                limit?: number;
                /** @description Só os profissionais que executam este serviço */
                serviceId?: string;
                /** @description Só tem efeito para administradores */
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalPageResponse"];
                };
            };
        };
    };
    ProfessionalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfessionalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalResponse"];
                };
            };
        };
    };
    ProfessionalsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalDetailResponse"];
                };
            };
        };
    };
    ProfessionalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfessionalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalResponse"];
                };
            };
        };
    };
    ProfessionalsController_replaceServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetServicesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalDetailResponse"];
                };
            };
        };
    };
    ProfessionalsController_replaceWorkingHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWorkingHoursDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessionalDetailResponse"];
                };
            };
        };
    };
    AppointmentsController_list: {
        parameters: {
            query?: {
                /** @description Página, começando em 1 */
                page?: number;
                /** @description Itens por página (máximo 100) */
                limit?: number;
                from?: string;
                to?: string;
                /** @description Repetível: ?itemStatus=PENDING&itemStatus=CONFIRMED */
                itemStatus?: ("PENDING" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "NO_SHOW")[];
                professionalId?: string;
                serviceId?: string;
                /** @description Só administrador */
                clientId?: string;
                /** @description Busca por nome/e-mail do cliente. Só administrador */
                q?: string;
                sort?: "startsAt" | "createdAt";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentPageResponse"];
                };
            };
        };
    };
    AppointmentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppointmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentHistoryEntryResponse"][];
                };
            };
        };
    };
    AppointmentsController_addAppointmentItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_repositionAppointmentItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositionItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                itemId: string;
                /** @description Transição operacional do item (administrador) */
                status: "confirmed" | "in-progress" | "completed" | "no-show";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AppointmentsController_cancelAppointmentItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
        };
    };
    AvailabilityController_get: {
        parameters: {
            query: {
                /** @description Data, no fuso do salão */
                date: string;
                /** @description Itens desejados, serviceId:professionalId separados por vírgula */
                items: components["schemas"]["AppointmentItemInputDto"][];
                /** @description Ordem sendo alterada (adicionar/reposicionar item) */
                appointmentId?: string;
                /** @description Item a ignorar ao reposicionar */
                excludeItemId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
        };
    };
    ConfigController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    ReportsController_weekly: {
        parameters: {
            query: {
                /** @description Qualquer data dentro da semana desejada */
                weekStart: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReportResponse"];
                };
            };
        };
    };
}
