export enum OutboxEventType {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  ITEMS_CONFIRMED = 'ITEMS_CONFIRMED',
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_REPOSITIONED = 'ITEM_REPOSITIONED',
  ITEMS_CANCELLED = 'ITEMS_CANCELLED',
  REMINDER_DUE = 'REMINDER_DUE',
}
