export const authLabels = {
  loginTitle: 'Entrar',
  loginSubtitle: 'Acesse sua conta para agendar',
  emailLabel: 'E-mail',
  emailPlaceholder: 'seu@email.com',
  passwordLabel: 'Senha',
  passwordPlaceholder: '••••••••',
  submit: 'Entrar',
  submitting: 'Entrando…',
  emailRequired: 'Informe o e-mail',
  emailInvalid: 'E-mail inválido',
  passwordRequired: 'Informe a senha',
  loggedInAs: (name: string) => `Olá, ${name}`,
  logout: 'Sair',
  registerTitle: 'Criar conta',
  registerSubtitle: 'Leva menos de um minuto',
  nameLabel: 'Nome',
  namePlaceholder: 'Seu nome completo',
  nameRequired: 'Informe o nome',
  nameTooShort: 'Nome deve ter pelo menos 2 letras',
  phoneLabel: 'Telefone',
  phoneOptionalHint: '(opcional)',
  phonePlaceholder: '(11) 91234-5678',
  passwordTooShort: 'Senha deve ter pelo menos 8 caracteres',
  registerSubmit: 'Criar conta',
  registerSubmitting: 'Criando conta…',
  haveAccount: 'Já tem conta?',
  noAccount: 'Não tem conta?',
  goToLogin: 'Entrar',
  goToRegister: 'Criar conta',
};
