export const bookingLabels = {
  wizardTitle: 'Novo agendamento',
  myAppointmentsLink: 'Meus agendamentos',
  step1Label: 'Passo 1 de 3 · Serviços',
  step1Hint: 'Escolha os serviços e o profissional de cada um',
  sameVisitHint: 'Os serviços escolhidos acontecem em sequência, sem intervalo, na mesma visita. Para horários separados (ex.: unha de manhã, corte à tarde), faça um agendamento para cada um.',
  chooseProfessional: 'Escolha o profissional',
  continueButton: 'Continuar',
  backButton: 'Voltar',
  minutesSuffix: 'min',
  selectedCount: (count: number) => (count === 1 ? '1 serviço selecionado' : `${count} serviços selecionados`),
  needProfessionalHint: 'Escolha um profissional para cada serviço selecionado',
  needAtLeastOneServiceHint: 'Selecione ao menos um serviço',
  loadingServices: 'Carregando serviços…',
  emptyServices: 'Nenhum serviço disponível no momento',
  loadingSlots: 'Carregando horários…',
  step2Label: 'Passo 2 de 3 · Data e horário',
  noSlotsAvailable: 'Nenhum horário disponível nesta data',
  sameWeekSuggestion: (date: string) =>
    `Você já tem um agendamento essa semana, em ${date}. Também há horários livres nessa data.`,
  useThisDate: 'Usar esta data',
  step3Label: 'Passo 3 de 3 · Revisão',
  notesLabel: 'Observação',
  notesOptionalHint: '(opcional)',
  notesPlaceholder: 'Alguma preferência ou observação para a Leila?',
  totalLabel: 'Total',
  confirmButton: 'Confirmar agendamento',
  confirming: 'Confirmando…',
  slotTakenTitle: 'Esse horário acabou de ser ocupado',
  slotTakenDescription: 'Escolha outro horário disponível',
  bookingConfirmedTitle: 'Agendamento confirmado!',
};
