export const catalogLabels = {
  servicesTitle: 'Serviços',
  newService: 'Novo serviço',
  editService: 'Editar serviço',
  nameLabel: 'Nome',
  durationLabel: 'Duração (min)',
  priceLabel: 'Preço (R$)',
  save: 'Salvar',
  saving: 'Salvando…',
  cancel: 'Cancelar',
  activate: 'Ativar',
  deactivate: 'Desativar',
  active: 'Ativo',
  inactive: 'Inativo',
  serviceSaved: 'Serviço salvo',
  professionalCreated: 'Profissional cadastrado',
  professionalNameSaved: 'Nome atualizado',
  professionalServicesSaved: 'Serviços atualizados',
  professionalHoursSaved: 'Expediente atualizado',
  professionalsTitle: 'Profissionais',
  newProfessional: 'Novo profissional',
  editProfessional: 'Editar profissional',
  servicesSectionTitle: 'Serviços executados',
  workingHoursSectionTitle: 'Expediente semanal',
  addWindow: 'Adicionar faixa',
  removeWindow: 'Remover',
  backToList: 'Voltar',
  loadMore: 'Carregar mais',
  weekdayLabels: ['', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
};
