export const queueLabels = {
  screenTitle: 'Fila de agendamentos',
  tabToday: 'Hoje',
  tabPending: 'Pendentes',
  tabUpcoming: 'Próximos',
  loading: 'Carregando…',
  empty: 'Nenhum agendamento por aqui',
  loadMore: 'Carregar mais',
  loadErrorTitle: 'Não foi possível carregar',
  loadErrorRetry: 'Tentar novamente',
  confirm: 'Confirmar',
  confirming: 'Confirmando…',
  confirmSuccess: 'Agendamento confirmado',
  cancelAppointment: 'Cancelar agendamento',
  cancelConfirmQuestion: 'Cancelar este agendamento?',
  cancelConfirmYes: 'Sim, cancelar',
  cancelConfirmNo: 'Não',
  cancelReasonLabel: 'Motivo',
  cancelReasonOptionalHint: '(opcional)',
  cancelReasonPlaceholder: 'Ex.: imprevisto de última hora',
  cancelling: 'Cancelando…',
  cancelItem: 'Cancelar item',
  cancelItemConfirmQuestion: 'Cancelar este item?',
  backToQueue: 'Fila de agendamentos',
  notFoundTitle: 'Agendamento não encontrado',
  totalLabel: 'Total',
  markConfirmed: 'Confirmar item',
  markInProgress: 'Iniciar atendimento',
  markCompleted: 'Concluir',
  markNoShow: 'Marcar falta',
  timelineTitle: 'Linha do tempo',
  timelineEmpty: 'Nenhum evento registrado ainda',
};

export const historyActionLabels: Record<string, string> = {
  ITEM_ADDED: 'Serviço adicionado',
  ITEM_REPOSITIONED: 'Horário alterado',
  ITEM_STATUS_CHANGED: 'Status alterado',
};
